# Generated by Django 2.2.1 on 2019-05-22 20:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('summer_driving_range', models.PositiveIntegerField(verbose_name='Summer driving range')),
                ('winter_driving_range', models.PositiveIntegerField(verbose_name='Winter driving range')),
                ('charging_time', models.PositiveIntegerField(verbose_name='Charging time')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='Description')),
                ('distance', models.PositiveIntegerField(verbose_name='Distance')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('start_time', models.DateTimeField(verbose_name='Start time')),
                ('end_time', models.DateTimeField(verbose_name='End time')),
                ('should_be_charged_fully', models.BooleanField(default=False, verbose_name='Should be charged fully')),
                ('priority', models.CharField(blank=True, choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='L', max_length=1, verbose_name='Priority')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.Car')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_color', models.CharField(default='#0275d8', max_length=7, verbose_name='Calendar color')),
                ('phone_number', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+32496123456'", regex='^\\+\\d{11}$')], verbose_name='Phone number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChargingReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start time')),
                ('end_time', models.DateTimeField(verbose_name='End time')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.Car')),
            ],
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['start_time'], name='reservation_start_t_616378_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['end_time'], name='reservation_end_tim_9da8ac_idx'),
        ),
        migrations.AddIndex(
            model_name='chargingreservation',
            index=models.Index(fields=['start_time'], name='reservation_start_t_0128c3_idx'),
        ),
        migrations.AddIndex(
            model_name='chargingreservation',
            index=models.Index(fields=['end_time'], name='reservation_end_tim_f12d76_idx'),
        ),
    ]
