# Generated by Django 2.2.1 on 2019-06-03 12:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.Car'),
        ),
        migrations.AlterField(
            model_name='car',
            name='charging_time',
            field=models.PositiveIntegerField(verbose_name='Oplaadtijd'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Naam'),
        ),
        migrations.AlterField(
            model_name='car',
            name='summer_driving_range',
            field=models.PositiveIntegerField(verbose_name='Rijbereik in de zomer'),
        ),
        migrations.AlterField(
            model_name='car',
            name='winter_driving_range',
            field=models.PositiveIntegerField(verbose_name='Rijbereik in de winter'),
        ),
        migrations.AlterField(
            model_name='chargingreservation',
            name='end_time',
            field=models.DateTimeField(verbose_name='Eindtijd'),
        ),
        migrations.AlterField(
            model_name='chargingreservation',
            name='start_time',
            field=models.DateTimeField(verbose_name='Starttijd'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='calendar_color',
            field=models.CharField(default='#0275d8', max_length=7, verbose_name='Kalenderkleur'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Telefoonnummer moet het volgende formaat hebben: '+32496123456'", regex='^\\+\\d{11}$')], verbose_name='Telefoonnummer'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Beschrijving'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='distance',
            field=models.PositiveIntegerField(verbose_name='Afstand'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.DateTimeField(verbose_name='Eindtijd'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Locatie'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='priority',
            field=models.CharField(blank=True, choices=[('L', 'Laag'), ('M', 'Medium'), ('H', 'Hoog')], default='L', max_length=1, verbose_name='Prioriteit'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='should_be_charged_fully',
            field=models.BooleanField(default=False, verbose_name='Moet volledig opgeladen zijn'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.DateTimeField(verbose_name='Starttijd'),
        ),
    ]
