# Generated by Django 2.2.1 on 2019-05-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20190511_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='distance',
            field=models.PositiveIntegerField(),
        ),
    ]
