# Generated by Django 2.2.1 on 2019-05-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20190524_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='renaultserviceslink',
            name='refresh_token',
            field=models.TextField(blank=True),
        ),
    ]
