# Generated by Django 2.2.1 on 2019-05-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20190512_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='distance',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
