# Generated by Django 2.2.1 on 2019-05-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20190512_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='distance',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
