# Generated by Django 2.2.1 on 2019-05-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_renaultserviceslink_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='renaultserviceslink',
            name='plugged',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
