# Generated by Django 2.2.1 on 2019-05-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='charging_time',
            field=models.PositiveIntegerField(default=6),
            preserve_default=False,
        ),
    ]
