# Generated by Django 2.2.1 on 2019-05-22 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_auto_20190521_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Telefoonnummer moet het volgende formaat hebben: '+32496123456'", regex='^\\+\\d{11}$')], verbose_name='Telefoonnummer'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['start_time'], name='reservation_start_t_616378_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['end_time'], name='reservation_end_tim_9da8ac_idx'),
        ),
    ]
